# Generated by Django 4.1.4 on 2022-12-27 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='addingBalanceCampaigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount_money', models.FloatField()),
                ('is_active', models.BooleanField(default=False)),
                ('gift_price', models.FloatField(default=0)),
                ('is_have_discount', models.BooleanField(default=False)),
                ('discount_percentage', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='branchs',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='superuser.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='branchs',
            name='branch',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
