# Generated by Django 4.1.4 on 2022-12-29 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0002_addingbalancecampaigns_branchs_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildOfGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=100)),
                ('parent_surname', models.CharField(max_length=100)),
                ('tel_no', models.CharField(max_length=100)),
                ('child_name', models.CharField(max_length=100)),
                ('child_surname', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('is_send_email', models.BooleanField(default=False)),
                ('company', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('game_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
