# Generated by Django 4.1.4 on 2023-02-20 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0003_childofgames'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branchs',
            old_name='branch',
            new_name='branch_name',
        ),
    ]
