# Generated by Django 4.1.4 on 2022-12-30 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_gift_game_company_giftdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jetonhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
