# Generated by Django 4.1.4 on 2023-01-02 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_jetonhistory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jetonconverisonhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
