# Generated by Django 4.1.4 on 2023-01-19 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_update_at_family_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftdetails',
            name='gift',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.gift'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='giftdetails',
            name='jeton_amount_of_gifts',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tel_no',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otpchange',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
