# Generated by Django 4.1.4 on 2023-02-19 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funparapercentage',
            old_name='total_funpara',
            new_name='total_funpuan',
        ),
    ]
